### ISSUE TITLE
Error when compiling C.

### ISSUE THREAD

**Issue by dxdiagmauric** [sonyxperiadev/device-sony-sumire#59]
Archive in dir: vendor/qcom/opensource/dataservices/rmnetctl/src/librmnetctl.c
Line 864.
request.message_type =RMNET_NETLINK_NEW_VND_WITH_NAME;
Change to:
request.message_type =RMNET_NETLINK_NEW_VND_WITH_PREFIX;

**Comment by jerpelea** [comment]
please send bugs to the bug tracker
